openapi: 3.0.1
info:
  title: 백투더퓨처 API Documentation
  description: 백투더퓨처 API 문서입니다.
  version: v1.0.0
servers:
- url: http://localhost:8080/v1
  description: Generated server url
security:
- Authorization: []
paths:
  /member/register:
    post:
      tags:
      - member-controller
      operationId: registerMember
      requestBody:
        content:
          application/json:
            schema:
              required:
              - request
              type: object
              properties:
                request:
                  $ref: '#/components/schemas/MemberRegisterDto'
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BfResponseObject'
  /member/refresh:
    post:
      tags:
      - member-controller
      operationId: refreshAccessToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequestDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BfResponseObject'
  /member/login:
    post:
      tags:
      - member-controller
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberLoginDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BfResponseObject'
  /member/login/oauth:
    post:
      tags:
      - member-controller
      operationId: oauthLogin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OAuthLoginDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BfResponseObject'
  /member/business/number/status:
    post:
      tags:
      - member-controller
      summary: 사업자 번호 상태 조회
      description: 입력된 사업자 정보의 유효성을 검증합니다.
      operationId: businessNumberStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessNumberValidateRequestDto'
        required: true
      responses:
        "200":
          description: 사업자 번호 검증 유효성 검사 결과
          content:
            application/json:
              examples:
                valid:
                  description: valid
                  value:
                    code: 200
                    message: 정상 처리되었습니다.
                    data:
                      isValid: true
                invalid:
                  description: invalid
                  value:
                    code: 200
                    message: 정상 처리되었습니다.
                    data:
                      isValid: false
      security: []
  /member/business/info/validation:
    post:
      tags:
      - member-controller
      summary: 사업자 정보 검증
      description: 입력된 사업자 정보의 유효성을 검증합니다.
      operationId: validateBusinessNumber
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessInfoValidateRequestDto'
        required: true
      responses:
        "200":
          description: 사업자 정보 검증 유효성 검사 결과
          content:
            application/json:
              examples:
                valid:
                  description: valid
                  value:
                    code: 200
                    message: 정상 처리되었습니다.
                    data:
                      isValid: true
                invalid:
                  description: invalid
                  value:
                    code: 200
                    message: 정상 처리되었습니다.
                    data:
                      isValid: false
      security: []
components:
  schemas:
    MemberRegisterDto:
      required:
      - email
      - name
      - password
      - passwordConfirm
      type: object
      properties:
        email:
          pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$"
          type: string
        name:
          maxLength: 50
          minLength: 2
          type: string
        password:
          maxLength: 2147483647
          minLength: 6
          type: string
        passwordConfirm:
          maxLength: 2147483647
          minLength: 6
          type: string
        phoneNumber:
          maxLength: 3
          minLength: 3
          type: string
    BfResponseObject:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        data:
          type: object
    RefreshTokenRequestDto:
      required:
      - refreshToken
      type: object
      properties:
        refreshToken:
          type: string
    MemberLoginDto:
      required:
      - email
      - password
      type: object
      properties:
        email:
          pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$"
          type: string
        password:
          maxLength: 2147483647
          minLength: 6
          type: string
    OAuthLoginDto:
      required:
      - authorizationCode
      - token
      type: object
      properties:
        authorizationCode:
          type: string
        providerType:
          type: string
          enum:
          - KAKAO
          - NAVER
          - GOOGLE
        rolesType:
          type: string
          enum:
          - ROLE_ADMIN
          - ROLE_USER
          - ROLE_STORE_OWNER
        state:
          type: string
        token:
          type: string
    BusinessNumberValidateRequestDto:
      required:
      - businessNumber
      type: object
      properties:
        businessNumber:
          type: string
          description: 사업자 번호
          example: 123-45-67890
    BusinessInfoValidateRequestDto:
      required:
      - businessNumber
      - name
      type: object
      properties:
        businessNumber:
          type: string
          description: 사업자 번호
          example: 123-45-67890
        startDate:
          type: string
          description: "개업 일자, yyyyMMdd 형식"
          example: "20220415"
        name:
          type: string
          description: 대표자 성명
          example: 홍길동
        name2:
          type: string
          description: 대표자 성명2
          example: 김철수
        businessName:
          type: string
          description: 대표자 성명2
          example: 김철수
        corporationNumber:
          type: string
          description: 상호
          example: OOO 기업
        businessSector:
          type: string
          description: 주업태명
          example: 제조업
        businessType:
          type: string
          description: 주종목명
          example: 전자제품
        businessAddress:
          type: string
          description: 사업장 주소
          example: 서울시 강남구 역삼동 123-45
  securitySchemes:
    Authorization:
      type: http
      name: Authorization
      scheme: bearer
      bearerFormat: JWT
